import React, { createContext, useContext, useState } from 'react';

type Language = 'pt' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<string, any> = {
  pt: {
    sidebar: {
      dashboard: 'Dashboard',
      inventory: 'Estoque',
      operations: 'Operações',
      transit: 'Trânsito',
      purchases: 'Compras',
      cashbox: 'Caixa',
      invoices: 'Faturas',
      checklists: 'Checklists',
      stores: 'Lojas',
      users: 'Usuários',
      settings: 'Configurações'
    },
    common: {
      product: 'Produto',
      quantity: 'Quantidade',
      status: 'Status',
      actions: 'Ações',
      error: 'Erro',
      cancel: 'Cancelar',
      update: 'Atualizar',
      add: 'Adicionar',
      save: 'Salvar',
      create: 'Criar',
      close: 'Fechar',
      name: 'Nome',
      units: 'unidades',
      notes: 'Observações',
      supplier: 'Fornecedor',
      priority: 'Prioridade',
      store: 'Loja',
      type: 'Tipo',
      active: 'Ativo',
      inactive: 'Inativo',
      select_product: 'Selecionar produto',
      select_store: 'Selecionar loja',
      select_supplier: 'Selecionar fornecedor'
    },
    dashboard: {
      title: 'Dashboard',
      overview: 'Visão Geral',
      totalStores: 'Total de Lojas',
      lowStockItems: 'Itens com Estoque Baixo',
      openCashRegisters: 'Caixas Abertos',
      overdueInvoices: 'Faturas Vencidas',
      recentActivity: 'Atividade Recente',
      quickActions: 'Ações Rápidas',
      addProduct: 'Adicionar Produto',
      openCash: 'Abrir Caixa',
      viewReports: 'Ver Relatórios',
      totalProducts: 'Total de Produtos',
      lowStock: 'Estoque Baixo',
      pendingInvoices: 'Faturas Pendentes',
      openCashbox: 'Caixas Abertos',
      recentMovements: 'Movimentações Recentes',
      alerts: 'Alertas',
      operationalSummary: 'Resumo Operacional',
      financialSummary: 'Resumo Financeiro',
      entry: 'Entrada',
      exit: 'Saída',
      transfer: 'Transferência',
      critical: 'Crítico',
      overdue: 'Vencida',
      invoice: 'Fatura',
      qty: 'Qtd'
    },
    inventory: {
      title: 'Gestão de Estoque',
      search: 'Buscar produtos...',
      filterByStore: 'Filtrar por loja',
      filterByCategory: 'Filtrar por categoria',
      product: 'Produto',
      sku: 'SKU',
      category: 'Categoria',
      store: 'Loja',
      stock: 'Estoque',
      minStock: 'Estoque Mínimo',
      actions: 'Ações',
      addProduct: 'Adicionar Produto',
      editProduct: 'Editar Produto',
      addMovement: 'Adicionar Movimento',
      costPrice: 'Preço de Custo',
      allCategories: 'Todas as Categorias',
      allStores: 'Todas as Lojas',
      allSuppliers: 'Todos os Fornecedores',
      noCategory: 'Sem Categoria',
      filterBySupplier: 'Filtrar por fornecedor',
      stockStatus: {
        normal: 'Estoque Normal',
        low: 'Estoque Baixo',
        critical: 'Estoque Crítico'
      },
      noProductsFilters: 'Nenhum produto encontrado com os filtros selecionados.',
      total: 'Total'
    },
    operations: {
      title: 'Operações',
      description: 'Gerencie retiradas e movimentações de estoque',
      history: 'Histórico',
      searchProducts: 'Buscar produtos...',
      selectStore: 'Selecionar loja',
      selectCategory: 'Selecionar categoria',
      allStores: 'Todas as lojas',
      allCategories: 'Todas as categorias',
      availableProducts: 'Produtos Disponíveis',
      withdraw: 'Retirar',
      units: 'unidades',
      noProductsAvailable: 'Nenhum produto disponível para retirada',
      recentOperations: 'Operações Recentes',
      product: 'Produto',
      quantity: 'Quantidade',
      date: 'Data',
      user: 'Usuário',
      noRecentOperations: 'Nenhuma operação recente',
      withdrawStock: 'Retirar Estoque',
      productInfo: 'Informações do Produto',
      productName: 'Nome do Produto',
      category: 'Categoria',
      sku: 'SKU',
      sellingPrice: 'Preço de Venda',
      store: 'Loja',
      currentStock: 'Estoque Atual',
      minimumStock: 'Estoque Mínimo',
      lowStockWarning: 'Atenção: Estoque baixo!',
      quantityToWithdraw: 'Quantidade a Retirar',
      enterQuantity: 'Digite a quantidade',
      remainingAfterWithdrawal: 'Restará após retirada',
      notes: 'Observações',
      optional: 'opcional',
      addNotes: 'Adicione observações sobre esta retirada...',
      recentMovements: 'Movimentações Recentes',
      cancel: 'Cancelar',
      confirmWithdrawal: 'Confirmar Retirada',
      processing: 'Processando...',
      error: 'Erro',
      success: 'Sucesso',
      selectStoreRequired: 'Selecione uma loja',
      invalidQuantity: 'Quantidade inválida',
      insufficientStock: 'Estoque insuficiente',
      lowStockAlert: 'Alerta de Estoque Baixo',
      belowMinimumStock: 'ficou abaixo do estoque mínimo',
      withdrawalCompleted: 'Retirada realizada com sucesso',
      withdrawalFailed: 'Falha ao realizar retirada'
    },
    transit: {
      title: 'Gestão de Trânsito',
      description: 'Gerencie transferências entre lojas',
      status_updated: 'Status Atualizado',
      movement: 'Movimentação',
      updated_to: 'atualizado para',
      all_status: 'Todos os status',
      pending: 'Pendente',
      in_transit: 'Em Trânsito',
      delivered: 'Entregue',
      new_transfer: 'Nova Transferência',
      total: 'Total',
      movements: 'Movimentações',
      from: 'Origem',
      to: 'Destino',
      created_at: 'Criado em',
      external: 'Externo',
      no_movements: 'Nenhuma movimentação encontrada',
      view_transfer: 'Ver Transferência',
      same_store_error: 'A loja de origem e destino não podem ser iguais',
      updated: 'Atualizado',
      movement_updated_successfully: 'Movimentação atualizada com sucesso',
      created: 'Criado',
      movement_created_successfully: 'Movimentação criada com sucesso',
      movement_details: 'Detalhes da Movimentação',
      movement_id: 'ID da Movimentação',
      transfer_summary: 'Resumo da Transferência',
      origin: 'Origem',
      destination: 'Destino',
      create_transfer: 'Criar Transferência',
      product_photo: 'Foto',
      filter_category: 'Categoria',
      filter_supplier: 'Fornecedor',
      filter_product: 'Produto',
      filter_origin: 'Loja Origem',
      filter_destination: 'Loja Destino',
      filter_status: 'Status',
      filters_title: 'Filtros',
      export_csv: 'Exportar CSV',
      export_title: 'Exportar Movimentações',
      export_start_date: 'Início',
      export_end_date: 'Fim',
      export_store: 'Loja',
      export_moved_qty: 'Quantidade movimentada',
      export_product: 'Produto',
      export_moved: 'Movimentado',
      export_balance: 'Saldo',
      export_download: 'Baixar CSV',
      export_no_data: 'Nenhum dado encontrado para o período selecionado',
      export_all_stores: 'Todas as Lojas',
      export_period: 'Período',
      export_quantity_csv: 'Quantidade'
    },
    purchases: {
      title: 'Sugestões de Compra',
      description: 'Produtos com estoque baixo que precisam ser repostos',
      orderCreated: 'Pedido Criado',
      orderFor: 'Pedido para',
      productDetails: 'Detalhes do Produto',
      currentStock: 'Estoque Atual',
      minStock: 'Estoque Mínimo',
      orderDetails: 'Detalhes do Pedido',
      quantity: 'Quantidade',
      orderNotes: 'Observações do pedido...',
      totalCost: 'Custo Total',
      unitPrice: 'Preço unitário',
      createOrder: 'Criar Pedido',
      allStores: 'Todas as Lojas',
      storesSelected: 'lojas selecionadas',
      allSuppliers: 'Todos os Fornecedores',
      allStatuses: 'Todos os Status',
      critical: 'Crítico',
      warning: 'Atenção',
      normal: 'Normal',
      generateOrder: 'Gerar Pedido',
      code: 'Código',
      unit: 'Medida',
      ideal: 'Ideal',
      suggestion: 'Sugestão',
      orderQty: 'Pedido',
      distributeByStore: 'Distribuir por loja',
      stockByStore: 'Estoque por loja',
      noItems: 'Nenhum item encontrado',
      noItemsDescription: 'Não há produtos com os filtros selecionados',
      distributeEvenly: 'Distribuir Igualmente',
      distributeByNeed: 'Por Necessidade da Loja',
      store: 'Loja',
      totalSuggested: 'Total Sugerido',
      qtyPlaceholder: 'Qtd',
      totalToOrder: 'Total a Pedir',
      ofSuggested: 'de {count} sugeridos',
      exceedsSuggested: 'Quantidade excede o sugerido',
      validDistribution: 'Distribuição válida',
      confirmDistribution: 'Confirmar Distribuição',
      orderSummary: 'Resumo do Pedido',
      products: 'produtos',
      units: 'unidades',
      storesLabel: 'lojas',
      suppliers: 'Fornecedores',
      storesServed: 'Lojas Atendidas',
      totalItems: 'Total de Itens',
      formattedOrder: 'Pedido Formatado',
      copyText: 'Copiar Texto',
      copied: 'Copiado!',
      copiedDescription: 'Pedido copiado para a área de transferência',
      copyError: 'Não foi possível copiar o pedido',
      createTransit: 'Criar Trânsito',
      transitCreation: 'Criação de produtos em trânsito',
      transitWillCreate: 'Serão criados {count} controles de produtos em trânsito.',
      orderNumberLabel: 'Pedido',
      orderNumberPlaceholder: 'Ex: 123456',
      observationLabel: 'Observação',
      observationPlaceholder: 'Adicione observações sobre o pedido...',
      transitNote: 'É possível adicionar número de pedido e observações posteriormente.',
      creating: 'Criando...',
      createTransitAndInvoice: 'Criar produtos em trânsito e controle de fatura',
      transitCreated: 'Trânsito Criado!',
      transitCreatedDescription: '{count} produtos foram adicionados ao sistema de trânsito',
      transitError: 'Erro ao criar trânsito',
      requiredFields: 'Campos obrigatórios',
      fillRequiredFields: 'Preencha o número do pedido e a observação'
    },
    orders: {
      title: 'Gestão de Pedidos',
      description: 'Gerencie seus pedidos de compra',
      listTitle: 'Lista de Pedidos',
      orderDetails: 'Detalhes do Pedido',
      createdAt: 'Criação',
      createdBy: 'Criado por',
      supplier: 'Fornecedor',
      user: 'Usuário',
      stores: 'Lojas',
      store: 'Loja',
      items: 'Itens',
      qty: 'Qtde',
      quantity: 'Quantidade',
      invoiceManagement: 'Gestão de Fatura',
      generatedTransit: 'Gerou Trânsito',
      invoice: 'Fatura',
      transit: 'Trânsito',
      yes: 'SIM',
      no: 'NÃO',
      back: 'Voltar',
      backToList: 'Lista de Compras',
      productName: 'Produtos',
      unitOfMeasure: 'Unidade de Medida',
      products: 'Produtos',
      noOrders: 'Nenhum pedido encontrado',
      noOrdersDescription: 'Não há pedidos com os filtros selecionados',
      deleted: 'Pedido Excluído',
      deletedDescription: 'O pedido foi excluído com sucesso'
    },
    production: {
      title: 'Gestão de Produção',
      subtitle: 'Controle de insumos → produtos finais + gestão de sobras',
      history: 'Histórico',
      hideHistory: 'Ocultar Histórico',
      viewHistory: 'Ver Histórico',
      newRecipe: 'Nova Fórmula',
      totalRecipes: 'Total Fórmulas',
      todayProductions: 'Produções Hoje',
      available: 'Disponíveis',
      blocked: 'Bloqueadas',
      availableRecipes: 'Fórmulas Disponíveis',
      produce: 'Produzir',
      insufficientStock: 'Estoque Insuficiente',
      insufficientStockDesc: 'Não há estoque suficiente para produzir esta receita.',
      ingredients: 'ingrediente(s)',
      noRecipes: 'Nenhuma fórmula cadastrada',
      createFirstRecipe: 'Criar primeira fórmula',
      historyTitle: 'Histórico de Produção',
      yield: 'Rendimento',
      leftovers: 'Sobras',
      startProduction: 'Iniciar Produção',
      execute: 'Executar',
      exportCsv: 'Exportar Histórico',
      recipe: 'Fórmula',
      date: 'Data',
      noHistory: 'Nenhuma produção registrada',
      exportTitle: 'Exportar Histórico de Produção',
      startDate: 'Data Início',
      endDate: 'Data Fim',
      store: 'Loja',
      allStores: 'Todas as Lojas',
      download: 'Baixar CSV',
      noDataExport: 'Nenhum dado encontrado para o período selecionado',
      productionRegistered: 'Produção Registrada',
      productionSuccess: 'Produção concluída com sucesso!',
      recipeCreated: 'Fórmula Criada',
      product: 'Produto',
      quantity: 'Quantidade',
      observations: 'Observações'
    },
    cashbox: {
      title: 'Gestão de Caixa',
      description: 'Controle de abertura e fechamento de caixas'
    },
    invoices: {
      title: 'Gestão de Faturas',
      description: 'Controle de faturas de fornecedores',
      updated: 'Atualizada',
      invoice_updated_successfully: 'Fatura atualizada com sucesso',
      added: 'Adicionada',
      invoice_added_successfully: 'Fatura adicionada com sucesso',
      number: 'Número',
      amount: 'Valor',
      pending: 'Pendente',
      paid: 'Paga',
      issue_date: 'Data de Emissão',
      due_date: 'Data de Vencimento'
    },
    checklists: {
      title: 'Checklists',
      description: 'Listas de verificação para operações diárias',
      opening: 'Abertura',
      opening_description: 'Checklist para abertura da loja',
      closing: 'Fechamento',
      closing_description: 'Checklist para fechamento da loja',
      quality: 'Qualidade',
      quality_description: 'Verificação de qualidade e processos',
      all_types: 'Todos os tipos',
      new_checklist: 'Novo Checklist'
    },
    settings: {
      title: 'Configurações',
      description: 'Configurações do sistema',
      stores: 'Lojas',
      categories: 'Categorias',
      suppliers: 'Fornecedores',
      users: 'Usuários',
      notifications: 'Notificações',
      security: 'Segurança',
      backup: 'Backup',
      stores_management: 'Gestão de Lojas',
      add_store: 'Adicionar Loja',
      address: 'Endereço',
      contact: 'Contato',
      store_updated: 'Loja Atualizada',
      store_updated_successfully: 'Loja atualizada com sucesso',
      store_added: 'Loja Adicionada',
      store_added_successfully: 'Loja adicionada com sucesso',
      store_active: 'Loja ativa',
      confirm_delete_store: 'Tem certeza que deseja excluir esta loja?',
      store_deleted: 'Loja Excluída',
      store_deleted_successfully: 'Loja excluída com sucesso',
      general: 'Geral',
      language: 'Idioma',
      timezone: 'Fuso Horário',
      currency: 'Moeda',
      low_stock_alerts: 'Alertas de Estoque Baixo',
      low_stock_description: 'Receber notificações quando produtos atingirem estoque mínimo',
      overdue_invoices: 'Faturas Vencidas',
      overdue_description: 'Receber notificações sobre faturas vencidas',
      email_notifications: 'Notificações por Email',
      email_description: 'Receber notificações por email',
      backup_restore: 'Backup e Restauração',
      backup_created: 'Backup Criado',
      backup_downloaded: 'Backup baixado com sucesso',
      export_data: 'Exportar Dados',
      export_description: 'Exportar todos os dados do sistema em formato JSON',
      export_now: 'Exportar Agora',
      import_data: 'Importar Dados',
      import_description: 'Importar dados de um arquivo de backup',
      import_file: 'Importar Arquivo',
      import_coming_soon: 'Funcionalidade em breve',
      system_info: 'Informações do Sistema',
      version: 'Versão',
      last_backup: 'Último Backup',
      never: 'Nunca',
      database: 'Banco de Dados',
      records: 'Registros'
    },
    stockPopup: {
      currentStock: 'Estoque atual',
      lastUpdate: 'Última atualização em',
      add: 'Adicionar',
      putInTransit: 'Colocar em trânsito',
      observationPlaceholder: 'Observação (opcional)',
      viewHistory: 'Ver Histórico',
      noHistory: 'Nenhum histórico encontrado',
      close: 'Fechar',
      addMeasures: 'Adicionar {count} medidas',
      stockUpdated: 'Estoque Atualizado',
      edit: 'Editar',
      alerts: 'Alertas',
      transfer: 'Transferir',
      delete: 'Apagar'
    },
    alertConfig: {
      title: 'Definir níveis de alerta',
      warning: 'Atenção',
      critical: 'Crítico',
      applyToAllStores: 'Alterar para todas as lojas',
      saved: 'Alertas Salvos',
      savedAllStores: 'Níveis de alerta atualizados em todas as lojas',
      savedThisStore: 'Níveis de alerta atualizados nesta loja'
    },
    transferDialog: {
      transfer: 'Transferir',
      available: 'Disponível',
      selectStore: 'Escolha a loja de destino',
      transferCreated: 'Transferência Criada'
    },
    operationsPage: {
      subtitle: 'Controle operacional da loja',
      tabWithdrawal: 'Retirada de Estoque',
      tabProduction: 'Gestão de Produção',
      searchPlaceholder: 'Buscar produto...',
      noProducts: 'Nenhum produto encontrado nesta loja',
      withdrawButton: 'Retirar {count} medida(s) do estoque',
      withdrawn: 'Retirado',
      lowStockAlert: 'Estoque Baixo!',
      remaining: 'restante(s)',
      historyWithdrawn: 'Retirado',
      historyAdded: 'Adicionado'
    },
    finance: {
      title: 'Resumo Financeiro',
      selectPeriod: 'Selecionar período',
      periods: {
        today: 'Hoje',
        last7days: 'Últimos 7 dias',
        last30days: 'Últimos 30 dias',
        last3months: 'Últimos 3 meses',
        lastYear: 'Último ano'
      },
      revenue: 'Receitas',
      expenses: 'Despesas',
      balance: 'Saldo Mensal',
      margin: 'Margem',
      financialFlow: 'Fluxo Financeiro (Últimos 6 Meses)',
      comparePeriod: 'em relação ao período anterior'
    }
  },
  en: {
    sidebar: {
      dashboard: 'Dashboard',
      inventory: 'Inventory',
      operations: 'Operations',
      transit: 'Transit',
      purchases: 'Purchases',
      cashbox: 'Cash',
      checklists: 'Checklists',
      stores: 'Stores',
      users: 'Users',
      settings: 'Settings'
    },
    common: {
      product: 'Product',
      quantity: 'Quantity',
      status: 'Status',
      actions: 'Actions',
      error: 'Error',
      cancel: 'Cancel',
      update: 'Update',
      add: 'Add',
      save: 'Save',
      create: 'Create',
      close: 'Close',
      name: 'Name',
      units: 'units',
      notes: 'Notes',
      supplier: 'Supplier',
      priority: 'Priority',
      store: 'Store',
      type: 'Type',
      active: 'Active',
      inactive: 'Inactive',
      select_product: 'Select product',
      select_store: 'Select store',
      select_supplier: 'Select supplier'
    },
    dashboard: {
      title: 'Dashboard',
      overview: 'Overview',
      totalStores: 'Total Stores',
      lowStockItems: 'Low Stock Items',
      openCashRegisters: 'Open Cash Registers',
      overdueInvoices: 'Overdue Invoices',
      recentActivity: 'Recent Activity',
      quickActions: 'Quick Actions',
      addProduct: 'Add Product',
      openCash: 'Open Cash',
      viewReports: 'View Reports',
      totalProducts: 'Total Products',
      lowStock: 'Low Stock',
      pendingInvoices: 'Pending Invoices',
      openCashbox: 'Open Cash Registers',
      recentMovements: 'Recent Movements',
      alerts: 'Alerts',
      operationalSummary: 'Operational Summary',
      financialSummary: 'Financial Summary',
      entry: 'Entry',
      exit: 'Exit',
      transfer: 'Transfer',
      critical: 'Critical',
      overdue: 'Overdue',
      invoice: 'Invoice',
      qty: 'Qty'
    },
    inventory: {
      title: 'Inventory Management',
      search: 'Search products...',
      filterByStore: 'Filter by store',
      filterByCategory: 'Filter by category',
      product: 'Product',
      sku: 'SKU',
      category: 'Category',
      store: 'Store',
      stock: 'Stock',
      minStock: 'Min Stock',
      actions: 'Actions',
      addProduct: 'Add Product',
      editProduct: 'Edit Product',
      addMovement: 'Add Movement',
      costPrice: 'Cost Price',
      allCategories: 'All Categories',
      allStores: 'All Stores',
      allSuppliers: 'All Suppliers',
      noCategory: 'No Category',
      filterBySupplier: 'Filter by supplier',
      stockStatus: {
        normal: 'Normal Stock',
        low: 'Low Stock',
        critical: 'Critical Stock'
      },
      noProductsFilters: 'No products found with selected filters.',
      total: 'Total'
    },
    operations: {
      title: 'Operations',
      description: 'Manage stock withdrawals and movements',
      history: 'History',
      searchProducts: 'Search products...',
      selectStore: 'Select store',
      selectCategory: 'Select category',
      allStores: 'All stores',
      allCategories: 'All categories',
      availableProducts: 'Available Products',
      withdraw: 'Withdraw',
      units: 'units',
      noProductsAvailable: 'No products available for withdrawal',
      recentOperations: 'Recent Operations',
      product: 'Product',
      quantity: 'Quantity',
      date: 'Date',
      user: 'User',
      noRecentOperations: 'No recent operations',
      withdrawStock: 'Withdraw Stock',
      productInfo: 'Product Information',
      productName: 'Product Name',
      category: 'Category',
      sku: 'SKU',
      sellingPrice: 'Selling Price',
      store: 'Store',
      currentStock: 'Current Stock',
      minimumStock: 'Minimum Stock',
      lowStockWarning: 'Warning: Low stock!',
      quantityToWithdraw: 'Quantity to Withdraw',
      enterQuantity: 'Enter quantity',
      remainingAfterWithdrawal: 'Will remain after withdrawal',
      notes: 'Notes',
      optional: 'optional',
      addNotes: 'Add notes about this withdrawal...',
      recentMovements: 'Recent Movements',
      cancel: 'Cancel',
      confirmWithdrawal: 'Confirm Withdrawal',
      processing: 'Processing...',
      error: 'Error',
      success: 'Success',
      selectStoreRequired: 'Select a store',
      invalidQuantity: 'Invalid quantity',
      insufficientStock: 'Insufficient stock',
      lowStockAlert: 'Low Stock Alert',
      belowMinimumStock: 'is below minimum stock',
      withdrawalCompleted: 'Withdrawal completed successfully',
      withdrawalFailed: 'Failed to perform withdrawal'
    },
    transit: {
      title: 'Transit Management',
      description: 'Manage transfers between stores',
      status_updated: 'Status Updated',
      movement: 'Movement',
      updated_to: 'updated to',
      all_status: 'All statuses',
      pending: 'Pending',
      in_transit: 'In Transit',
      delivered: 'Delivered',
      new_transfer: 'New Transfer',
      total: 'Total',
      movements: 'Movements',
      from: 'From',
      to: 'To',
      created_at: 'Created at',
      external: 'External',
      no_movements: 'No movements found',
      view_transfer: 'View Transfer',
      same_store_error: 'Origin and destination stores cannot be the same',
      updated: 'Updated',
      movement_updated_successfully: 'Movement updated successfully',
      created: 'Created',
      movement_created_successfully: 'Movement created successfully',
      movement_details: 'Movement Details',
      movement_id: 'Movement ID',
      transfer_summary: 'Transfer Summary',
      origin: 'Origin',
      destination: 'Destination',
      create_transfer: 'Create Transfer',
      product_photo: 'Photo',
      filter_category: 'Category',
      filter_supplier: 'Supplier',
      filter_product: 'Product',
      filter_origin: 'Origin Store',
      filter_destination: 'Destination Store',
      filter_status: 'Status',
      filters_title: 'Filters',
      export_csv: 'Export CSV',
      export_title: 'Export Movements',
      export_start_date: 'Start',
      export_end_date: 'End',
      export_store: 'Store',
      export_moved_qty: 'Moved quantity',
      export_product: 'Product',
      export_moved: 'Moved',
      export_balance: 'Balance',
      export_download: 'Download CSV',
      export_no_data: 'No data found for the selected period',
      export_all_stores: 'All Stores',
      export_period: 'Period',
      export_quantity_csv: 'Quantity'
    },
    purchases: {
      title: 'Purchase Suggestions',
      description: 'Low stock products that need replenishment',
      orderCreated: 'Order Created',
      orderFor: 'Order for',
      productDetails: 'Product Details',
      currentStock: 'Current Stock',
      minStock: 'Minimum Stock',
      orderDetails: 'Order Details',
      quantity: 'Quantity',
      orderNotes: 'Order notes...',
      totalCost: 'Total Cost',
      unitPrice: 'Unit price',
      createOrder: 'Create Order',
      allStores: 'All Stores',
      storesSelected: 'stores selected',
      allSuppliers: 'All Suppliers',
      allStatuses: 'All Statuses',
      critical: 'Critical',
      warning: 'Warning',
      normal: 'Normal',
      generateOrder: 'Generate Order',
      code: 'Code',
      unit: 'Unit',
      ideal: 'Ideal',
      suggestion: 'Suggestion',
      orderQty: 'Order',
      distributeByStore: 'Distribute by store',
      stockByStore: 'Stock by store',
      noItems: 'No items found',
      noItemsDescription: 'No products match the selected filters',
      distributeEvenly: 'Distribute Evenly',
      distributeByNeed: 'By Store Need',
      store: 'Store',
      totalSuggested: 'Total Suggested',
      qtyPlaceholder: 'Qty',
      totalToOrder: 'Total to Order',
      ofSuggested: 'of {count} suggested',
      exceedsSuggested: 'Quantity exceeds suggested',
      validDistribution: 'Valid distribution',
      confirmDistribution: 'Confirm Distribution',
      orderSummary: 'Order Summary',
      products: 'products',
      units: 'units',
      storesLabel: 'stores',
      suppliers: 'Suppliers',
      storesServed: 'Stores Served',
      totalItems: 'Total Items',
      formattedOrder: 'Formatted Order',
      copyText: 'Copy Text',
      copied: 'Copied!',
      copiedDescription: 'Order copied to clipboard',
      copyError: 'Could not copy order',
      createTransit: 'Create Transit',
      transitCreation: 'Transit products creation',
      transitWillCreate: '{count} transit product controls will be created.',
      orderNumberLabel: 'Order',
      orderNumberPlaceholder: 'E.g.: 123456',
      observationLabel: 'Observation',
      observationPlaceholder: 'Add observations about the order...',
      transitNote: 'You can add order number and observations later.',
      creating: 'Creating...',
      createTransitAndInvoice: 'Create transit products and invoice control',
      transitCreated: 'Transit Created!',
      transitCreatedDescription: '{count} products were added to the transit system',
      transitError: 'Error creating transit',
      requiredFields: 'Required fields',
      fillRequiredFields: 'Fill in order number and observation'
    },
    orders: {
      title: 'Order Management',
      description: 'Manage your purchase orders',
      listTitle: 'Order List',
      orderDetails: 'Order Details',
      createdAt: 'Created',
      createdBy: 'Created by',
      supplier: 'Supplier',
      user: 'User',
      stores: 'Stores',
      store: 'Store',
      items: 'Items',
      qty: 'Qty',
      quantity: 'Quantity',
      invoiceManagement: 'Invoice Management',
      generatedTransit: 'Generated Transit',
      invoice: 'Invoice',
      transit: 'Transit',
      yes: 'YES',
      no: 'NO',
      back: 'Back',
      backToList: 'Purchase List',
      productName: 'Products',
      unitOfMeasure: 'Unit of Measure',
      products: 'Products',
      noOrders: 'No orders found',
      noOrdersDescription: 'No orders match the selected filters',
      deleted: 'Order Deleted',
      deletedDescription: 'The order was successfully deleted'
    },
    production: {
      title: 'Production Management',
      subtitle: 'Input control → final products + leftovers management',
      history: 'History',
      hideHistory: 'Hide History',
      viewHistory: 'View History',
      newRecipe: 'New Formula',
      totalRecipes: 'Total Formulas',
      todayProductions: 'Today Productions',
      available: 'Available',
      blocked: 'Blocked',
      availableRecipes: 'Available Formulas',
      produce: 'Produce',
      insufficientStock: 'Insufficient Stock',
      insufficientStockDesc: 'Not enough stock to produce this recipe.',
      ingredients: 'ingredient(s)',
      noRecipes: 'No formulas registered',
      createFirstRecipe: 'Create first formula',
      historyTitle: 'Production History',
      yield: 'Yield',
      leftovers: 'Leftovers',
      startProduction: 'Start Production',
      execute: 'Execute',
      exportCsv: 'Export History',
      recipe: 'Formula',
      date: 'Date',
      noHistory: 'No production records',
      exportTitle: 'Export Production History',
      startDate: 'Start Date',
      endDate: 'End Date',
      store: 'Store',
      allStores: 'All Stores',
      download: 'Download CSV',
      noDataExport: 'No data found for the selected period',
      productionRegistered: 'Production Registered',
      productionSuccess: 'Production completed successfully!',
      recipeCreated: 'Formula Created',
      product: 'Product',
      quantity: 'Quantity',
      observations: 'Observations'
    },
    cashbox: {
      title: 'Cash Management',
      description: 'Control cash register opening and closing'
    },
    invoices: {
      title: 'Invoice Management',
      description: 'Supplier invoice control',
      updated: 'Updated',
      invoice_updated_successfully: 'Invoice updated successfully',
      added: 'Added',
      invoice_added_successfully: 'Invoice added successfully',
      number: 'Number',
      amount: 'Amount',
      pending: 'Pending',
      paid: 'Paid',
      issue_date: 'Issue Date',
      due_date: 'Due Date'
    },
    checklists: {
      title: 'Checklists',
      description: 'Verification lists for daily operations',
      opening: 'Opening',
      opening_description: 'Store opening checklist',
      closing: 'Closing',
      closing_description: 'Store closing checklist',
      quality: 'Quality',
      quality_description: 'Quality and process verification',
      all_types: 'All types',
      new_checklist: 'New Checklist'
    },
    settings: {
      title: 'Settings',
      description: 'System settings',
      stores: 'Stores',
      categories: 'Categories',
      suppliers: 'Suppliers',
      users: 'Users',
      notifications: 'Notifications',
      security: 'Security',
      backup: 'Backup',
      stores_management: 'Store Management',
      add_store: 'Add Store',
      address: 'Address',
      contact: 'Contact',
      store_updated: 'Store Updated',
      store_updated_successfully: 'Store updated successfully',
      store_added: 'Store Added',
      store_added_successfully: 'Store added successfully',
      store_active: 'Store active',
      confirm_delete_store: 'Are you sure you want to delete this store?',
      store_deleted: 'Store Deleted',
      store_deleted_successfully: 'Store deleted successfully',
      general: 'General',
      language: 'Language',
      timezone: 'Timezone',
      currency: 'Currency',
      low_stock_alerts: 'Low Stock Alerts',
      low_stock_description: 'Receive notifications when products reach minimum stock',
      overdue_invoices: 'Overdue Invoices',
      overdue_description: 'Receive notifications about overdue invoices',
      email_notifications: 'Email Notifications',
      email_description: 'Receive notifications by email',
      backup_restore: 'Backup & Restore',
      backup_created: 'Backup Created',
      backup_downloaded: 'Backup downloaded successfully',
      export_data: 'Export Data',
      export_description: 'Export all system data in JSON format',
      export_now: 'Export Now',
      import_data: 'Import Data',
      import_description: 'Import data from a backup file',
      import_file: 'Import File',
      import_coming_soon: 'Coming soon',
      system_info: 'System Information',
      version: 'Version',
      last_backup: 'Last Backup',
      never: 'Never',
      database: 'Database',
      records: 'Records'
    },
    stockPopup: {
      currentStock: 'Current stock',
      lastUpdate: 'Last update on',
      add: 'Add',
      putInTransit: 'Put in transit',
      observationPlaceholder: 'Observation (optional)',
      viewHistory: 'View History',
      noHistory: 'No history found',
      close: 'Close',
      addMeasures: 'Add {count} measures',
      stockUpdated: 'Stock Updated',
      edit: 'Edit',
      alerts: 'Alerts',
      transfer: 'Transfer',
      delete: 'Delete'
    },
    alertConfig: {
      title: 'Set alert levels',
      warning: 'Warning',
      critical: 'Critical',
      applyToAllStores: 'Apply to all stores',
      saved: 'Alerts Saved',
      savedAllStores: 'Alert levels updated in all stores',
      savedThisStore: 'Alert levels updated for this store'
    },
    transferDialog: {
      transfer: 'Transfer',
      available: 'Available',
      selectStore: 'Select destination store',
      transferCreated: 'Transfer Created'
    },
    operationsPage: {
      subtitle: 'Store operational control',
      tabWithdrawal: 'Stock Withdrawal',
      tabProduction: 'Production Management',
      searchPlaceholder: 'Search product...',
      noProducts: 'No products found in this store',
      withdrawButton: 'Withdraw {count} measure(s) from stock',
      withdrawn: 'Withdrawn',
      lowStockAlert: 'Low Stock!',
      remaining: 'remaining',
      historyWithdrawn: 'Withdrawn',
      historyAdded: 'Added'
    },
    finance: {
      title: 'Financial Summary',
      selectPeriod: 'Select period',
      periods: {
        today: 'Today',
        last7days: 'Last 7 days',
        last30days: 'Last 30 days',
        last3months: 'Last 3 months',
        lastYear: 'Last year'
      },
      revenue: 'Revenue',
      expenses: 'Expenses',
      balance: 'Monthly Balance',
      margin: 'Margin',
      financialFlow: 'Financial Flow (Last 6 Months)',
      comparePeriod: 'vs previous period'
    }
  },
  es: {
    sidebar: {
      dashboard: 'Dashboard',
      inventory: 'Inventario',
      operations: 'Operaciones',
      transit: 'Tránsito',
      purchases: 'Compras',
      cashbox: 'Caja',
      invoices: 'Facturas',
      checklists: 'Listas',
      stores: 'Tiendas',
      users: 'Usuarios',
      settings: 'Configuraciones'
    },
    common: {
      product: 'Producto',
      quantity: 'Cantidad',
      status: 'Estado',
      actions: 'Acciones',
      error: 'Error',
      cancel: 'Cancelar',
      update: 'Actualizar',
      add: 'Agregar',
      save: 'Guardar',
      create: 'Crear',
      close: 'Cerrar',
      name: 'Nombre',
      units: 'unidades',
      notes: 'Notas',
      supplier: 'Proveedor',
      priority: 'Prioridad',
      store: 'Tienda',
      type: 'Tipo',
      active: 'Activo',
      inactive: 'Inactivo',
      select_product: 'Seleccionar producto',
      select_store: 'Seleccionar tienda',
      select_supplier: 'Seleccionar proveedor'
    },
    dashboard: {
      title: 'Dashboard',
      overview: 'Resumen',
      totalStores: 'Total de Tiendas',
      lowStockItems: 'Artículos con Stock Bajo',
      openCashRegisters: 'Cajas Abiertas',
      overdueInvoices: 'Facturas Vencidas',
      recentActivity: 'Actividad Reciente',
      quickActions: 'Acciones Rápidas',
      addProduct: 'Agregar Producto',
      openCash: 'Abrir Caja',
      viewReports: 'Ver Reportes',
      totalProducts: 'Total de Productos',
      lowStock: 'Stock Bajo',
      pendingInvoices: 'Facturas Pendientes',
      openCashbox: 'Cajas Abiertas',
      recentMovements: 'Movimientos Recientes',
      alerts: 'Alertas',
      operationalSummary: 'Resumen Operativo',
      financialSummary: 'Resumen Financiero',
      entry: 'Entrada',
      exit: 'Salida',
      transfer: 'Transferencia',
      critical: 'Crítico',
      overdue: 'Vencida',
      invoice: 'Factura',
      qty: 'Cant'
    },
    inventory: {
      title: 'Gestión de Inventario',
      search: 'Buscar productos...',
      filterByStore: 'Filtrar por tienda',
      filterByCategory: 'Filtrar por categoría',
      product: 'Producto',
      sku: 'SKU',
      category: 'Categoría',
      store: 'Tienda',
      stock: 'Stock',
      minStock: 'Stock Mínimo',
      actions: 'Acciones',
      addProduct: 'Agregar Producto',
      editProduct: 'Editar Producto',
      addMovement: 'Agregar Movimiento',
      costPrice: 'Precio de Costo',
      allCategories: 'Todas las Categorías',
      allStores: 'Todas las Tiendas',
      allSuppliers: 'Todos los Proveedores',
      noCategory: 'Sin Categoría',
      filterBySupplier: 'Filtrar por proveedor',
      stockStatus: {
        normal: 'Stock Normal',
        low: 'Stock Bajo',
        critical: 'Stock Crítico'
      },
      noProductsFilters: 'No se encontraron productos con los filtros seleccionados.',
      total: 'Total'
    },
    operations: {
      title: 'Operaciones',
      description: 'Gestiona retiros y movimientos de inventario',
      history: 'Historial',
      searchProducts: 'Buscar productos...',
      selectStore: 'Seleccionar tienda',
      selectCategory: 'Seleccionar categoría',
      allStores: 'Todas las tiendas',
      allCategories: 'Todas las categorías',
      availableProducts: 'Productos Disponibles',
      withdraw: 'Retirar',
      units: 'unidades',
      noProductsAvailable: 'No hay productos disponibles para retiro',
      recentOperations: 'Operaciones Recientes',
      product: 'Producto',
      quantity: 'Cantidad',
      date: 'Fecha',
      user: 'Usuario',
      noRecentOperations: 'No hay operaciones recientes',
      withdrawStock: 'Retirar Inventario',
      productInfo: 'Información del Producto',
      productName: 'Nombre del Producto',
      category: 'Categoría',
      sku: 'SKU',
      sellingPrice: 'Precio de Venta',
      store: 'Tienda',
      currentStock: 'Inventario Actual',
      minimumStock: 'Inventario Mínimo',
      lowStockWarning: '¡Advertencia: Inventario bajo!',
      quantityToWithdraw: 'Cantidad a Retirar',
      enterQuantity: 'Ingrese la cantidad',
      remainingAfterWithdrawal: 'Quedará después del retiro',
      notes: 'Notas',
      optional: 'opcional',
      addNotes: 'Agregue notas sobre este retiro...',
      recentMovements: 'Movimientos Recientes',
      cancel: 'Cancelar',
      confirmWithdrawal: 'Confirmar Retiro',
      processing: 'Procesando...',
      error: 'Error',
      success: 'Éxito',
      selectStoreRequired: 'Seleccione una tienda',
      invalidQuantity: 'Cantidad inválida',
      insufficientStock: 'Inventario insuficiente',
      lowStockAlert: 'Alerta de Inventario Bajo',
      belowMinimumStock: 'está por debajo del inventario mínimo',
      withdrawalCompleted: 'Retiro completado exitosamente',
      withdrawalFailed: 'Error al realizar el retiro'
    },
    transit: {
      title: 'Gestión de Tránsito',
      description: 'Gestionar transferencias entre tiendas',
      status_updated: 'Estado Actualizado',
      movement: 'Movimiento',
      updated_to: 'actualizado a',
      all_status: 'Todos los estados',
      pending: 'Pendiente',
      in_transit: 'En Tránsito',
      delivered: 'Entregado',
      new_transfer: 'Nueva Transferencia',
      total: 'Total',
      movements: 'Movimientos',
      from: 'Origen',
      to: 'Destino',
      created_at: 'Creado el',
      external: 'Externo',
      no_movements: 'Ningún movimiento encontrado',
      view_transfer: 'Ver Transferencia',
      same_store_error: 'Las tiendas de origen y destino no pueden ser iguales',
      updated: 'Actualizado',
      movement_updated_successfully: 'Movimiento actualizado exitosamente',
      created: 'Creado',
      movement_created_successfully: 'Movimiento creado exitosamente',
      movement_details: 'Detalles del Movimiento',
      movement_id: 'ID del Movimiento',
      transfer_summary: 'Resumen de Transferencia',
      origin: 'Origen',
      destination: 'Destino',
      create_transfer: 'Crear Transferencia',
      product_photo: 'Foto',
      filter_category: 'Categoría',
      filter_supplier: 'Proveedor',
      filter_product: 'Producto',
      filter_origin: 'Tienda Origen',
      filter_destination: 'Tienda Destino',
      filter_status: 'Estado',
      filters_title: 'Filtros',
      export_csv: 'Exportar CSV',
      export_title: 'Exportar Movimientos',
      export_start_date: 'Inicio',
      export_end_date: 'Fin',
      export_store: 'Tienda',
      export_moved_qty: 'Cantidad movida',
      export_product: 'Producto',
      export_moved: 'Movido',
      export_balance: 'Saldo',
      export_download: 'Descargar CSV',
      export_no_data: 'No se encontraron datos para el período seleccionado',
      export_all_stores: 'Todas las Tiendas',
      export_period: 'Período',
      export_quantity_csv: 'Cantidad'
    },
    purchases: {
      title: 'Sugerencias de Compra',
      description: 'Productos con stock bajo que necesitan reposición',
      orderCreated: 'Pedido Creado',
      orderFor: 'Pedido para',
      productDetails: 'Detalles del Producto',
      currentStock: 'Inventario Actual',
      minStock: 'Inventario Mínimo',
      orderDetails: 'Detalles del Pedido',
      quantity: 'Cantidad',
      orderNotes: 'Notas del pedido...',
      totalCost: 'Costo Total',
      unitPrice: 'Precio unitario',
      createOrder: 'Crear Pedido',
      allStores: 'Todas las Tiendas',
      storesSelected: 'tiendas seleccionadas',
      allSuppliers: 'Todos los Proveedores',
      allStatuses: 'Todos los Estados',
      critical: 'Crítico',
      warning: 'Atención',
      normal: 'Normal',
      generateOrder: 'Generar Pedido',
      code: 'Código',
      unit: 'Medida',
      ideal: 'Ideal',
      suggestion: 'Sugerencia',
      orderQty: 'Pedido',
      distributeByStore: 'Distribuir por tienda',
      stockByStore: 'Stock por tienda',
      noItems: 'Ningún artículo encontrado',
      noItemsDescription: 'No hay productos con los filtros seleccionados',
      distributeEvenly: 'Distribuir Igualmente',
      distributeByNeed: 'Por Necesidad de la Tienda',
      store: 'Tienda',
      totalSuggested: 'Total Sugerido',
      qtyPlaceholder: 'Ctd',
      totalToOrder: 'Total a Pedir',
      ofSuggested: 'de {count} sugeridos',
      exceedsSuggested: 'Cantidad excede lo sugerido',
      validDistribution: 'Distribución válida',
      confirmDistribution: 'Confirmar Distribución',
      orderSummary: 'Resumen del Pedido',
      products: 'productos',
      units: 'unidades',
      storesLabel: 'tiendas',
      suppliers: 'Proveedores',
      storesServed: 'Tiendas Atendidas',
      totalItems: 'Total de Ítems',
      formattedOrder: 'Pedido Formateado',
      copyText: 'Copiar Texto',
      copied: '¡Copiado!',
      copiedDescription: 'Pedido copiado al portapapeles',
      copyError: 'No se pudo copiar el pedido',
      createTransit: 'Crear Tránsito',
      transitCreation: 'Creación de productos en tránsito',
      transitWillCreate: 'Se crearán {count} controles de productos en tránsito.',
      orderNumberLabel: 'Pedido',
      orderNumberPlaceholder: 'Ej: 123456',
      observationLabel: 'Observación',
      observationPlaceholder: 'Agregue observaciones sobre el pedido...',
      transitNote: 'Es posible agregar número de pedido y observaciones posteriormente.',
      creating: 'Creando...',
      createTransitAndInvoice: 'Crear productos en tránsito y control de factura',
      transitCreated: '¡Tránsito Creado!',
      transitCreatedDescription: '{count} productos fueron agregados al sistema de tránsito',
      transitError: 'Error al crear tránsito',
      requiredFields: 'Campos obligatorios',
      fillRequiredFields: 'Complete el número de pedido y la observación'
    },
    orders: {
      title: 'Gestión de Pedidos',
      description: 'Gestione sus pedidos de compra',
      listTitle: 'Lista de Pedidos',
      orderDetails: 'Detalles del Pedido',
      createdAt: 'Creación',
      createdBy: 'Creado por',
      supplier: 'Proveedor',
      user: 'Usuario',
      stores: 'Tiendas',
      store: 'Tienda',
      items: 'Ítems',
      qty: 'Ctd',
      quantity: 'Cantidad',
      invoiceManagement: 'Gestión de Factura',
      generatedTransit: 'Generó Tránsito',
      invoice: 'Factura',
      transit: 'Tránsito',
      yes: 'SÍ',
      no: 'NO',
      back: 'Volver',
      backToList: 'Lista de Compras',
      productName: 'Productos',
      unitOfMeasure: 'Unidad de Medida',
      products: 'Productos',
      noOrders: 'Ningún pedido encontrado',
      noOrdersDescription: 'No hay pedidos con los filtros seleccionados',
      deleted: 'Pedido Eliminado',
      deletedDescription: 'El pedido fue eliminado exitosamente'
    },
    cashbox: {
      title: 'Gestión de Caja',
      description: 'Control de apertura y cierre de cajas'
    },
    invoices: {
      title: 'Gestión de Facturas',
      description: 'Control de facturas de proveedores',
      updated: 'Actualizada',
      invoice_updated_successfully: 'Factura actualizada exitosamente',
      added: 'Agregada',
      invoice_added_successfully: 'Factura agregada exitosamente',
      number: 'Número',
      amount: 'Monto',
      pending: 'Pendiente',
      paid: 'Pagada',
      issue_date: 'Fecha de Emisión',
      due_date: 'Fecha de Vencimiento'
    },
    checklists: {
      title: 'Listas de Verificación',
      description: 'Listas de verificación para operaciones diarias',
      opening: 'Apertura',
      opening_description: 'Lista de verificación para apertura de tienda',
      closing: 'Cierre',
      closing_description: 'Lista de verificación para cierre de tienda',
      quality: 'Calidad',
      quality_description: 'Verificación de calidad y procesos',
      all_types: 'Todos los tipos',
      new_checklist: 'Nueva Lista'
    },
    settings: {
      title: 'Configuraciones',
      description: 'Configuraciones del sistema',
      stores: 'Tiendas',
      categories: 'Categorías',
      suppliers: 'Proveedores',
      users: 'Usuarios',
      notifications: 'Notificaciones',
      security: 'Seguridad',
      backup: 'Respaldo',
      stores_management: 'Gestión de Tiendas',
      add_store: 'Agregar Tienda',
      address: 'Dirección',
      contact: 'Contacto',
      store_updated: 'Tienda Actualizada',
      store_updated_successfully: 'Tienda actualizada exitosamente',
      store_added: 'Tienda Agregada',
      store_added_successfully: 'Tienda agregada exitosamente',
      store_active: 'Tienda activa',
      confirm_delete_store: '¿Está seguro de que desea eliminar esta tienda?',
      store_deleted: 'Tienda Eliminada',
      store_deleted_successfully: 'Tienda eliminada exitosamente',
      general: 'General',
      language: 'Idioma',
      timezone: 'Zona Horaria',
      currency: 'Moneda',
      low_stock_alerts: 'Alertas de Inventario Bajo',
      low_stock_description: 'Recibir notificaciones cuando los productos alcancen el inventario mínimo',
      overdue_invoices: 'Facturas Vencidas',
      overdue_description: 'Recibir notificaciones sobre facturas vencidas',
      email_notifications: 'Notificaciones por Email',
      email_description: 'Recibir notificaciones por email',
      backup_restore: 'Respaldo y Restauración',
      backup_created: 'Respaldo Creado',
      backup_downloaded: 'Respaldo descargado exitosamente',
      export_data: 'Exportar Datos',
      export_description: 'Exportar todos los datos del sistema en formato JSON',
      export_now: 'Exportar Ahora',
      import_data: 'Importar Datos',
      import_description: 'Importar datos de un archivo de respaldo',
      import_file: 'Importar Archivo',
      import_coming_soon: 'Próximamente',
      system_info: 'Información del Sistema',
      version: 'Versión',
      last_backup: 'Último Respaldo',
      never: 'Nunca',
      database: 'Base de Datos',
      records: 'Registros'
    },
    stockPopup: {
      currentStock: 'Stock actual',
      lastUpdate: 'Última actualización el',
      add: 'Agregar',
      putInTransit: 'Colocar en tránsito',
      observationPlaceholder: 'Observación (opcional)',
      viewHistory: 'Ver Historial',
      noHistory: 'Sin historial',
      close: 'Cerrar',
      addMeasures: 'Agregar {count} medidas',
      stockUpdated: 'Stock Actualizado',
      edit: 'Editar',
      alerts: 'Alertas',
      transfer: 'Transferir',
      delete: 'Eliminar'
    },
    alertConfig: {
      title: 'Definir niveles de alerta',
      warning: 'Atención',
      critical: 'Crítico',
      applyToAllStores: 'Aplicar a todas las tiendas',
      saved: 'Alertas Guardadas',
      savedAllStores: 'Niveles de alerta actualizados en todas las tiendas',
      savedThisStore: 'Niveles de alerta actualizados en esta tienda'
    },
    transferDialog: {
      transfer: 'Transferir',
      available: 'Disponible',
      selectStore: 'Seleccione la tienda de destino',
      transferCreated: 'Transferencia Creada'
    },
    production: {
      title: 'Gestión de Producción',
      subtitle: 'Control de insumos → productos finales + gestión de sobras',
      history: 'Historial',
      hideHistory: 'Ocultar Historial',
      viewHistory: 'Ver Historial',
      newRecipe: 'Nueva Fórmula',
      totalRecipes: 'Total Fórmulas',
      todayProductions: 'Producciones Hoy',
      available: 'Disponibles',
      blocked: 'Bloqueadas',
      availableRecipes: 'Fórmulas Disponibles',
      produce: 'Producir',
      insufficientStock: 'Stock Insuficiente',
      insufficientStockDesc: 'No hay stock suficiente para producir esta receta.',
      ingredients: 'ingrediente(s)',
      noRecipes: 'Ninguna fórmula registrada',
      createFirstRecipe: 'Crear primera fórmula',
      historyTitle: 'Historial de Producción',
      yield: 'Rendimiento',
      leftovers: 'Sobras',
      startProduction: 'Iniciar Producción',
      execute: 'Ejecutar',
      exportCsv: 'Exportar Historial',
      recipe: 'Fórmula',
      date: 'Fecha',
      noHistory: 'Ninguna producción registrada',
      exportTitle: 'Exportar Historial de Producción',
      startDate: 'Fecha Inicio',
      endDate: 'Fecha Fin',
      store: 'Tienda',
      allStores: 'Todas las Tiendas',
      download: 'Descargar CSV',
      noDataExport: 'No se encontraron datos para el período seleccionado',
      productionRegistered: 'Producción Registrada',
      productionSuccess: '¡Producción completada con éxito!',
      recipeCreated: 'Fórmula Creada',
      product: 'Producto',
      quantity: 'Cantidad',
      observations: 'Observaciones'
    },
    operationsPage: {
      subtitle: 'Control operacional de la tienda',
      tabWithdrawal: 'Retiro de Stock',
      tabProduction: 'Gestión de Producción',
      searchPlaceholder: 'Buscar producto...',
      noProducts: 'No se encontraron productos en esta tienda',
      withdrawButton: 'Retirar {count} medida(s) del stock',
      withdrawn: 'Retirado',
      lowStockAlert: '¡Stock Bajo!',
      remaining: 'restante(s)',
      historyWithdrawn: 'Retirado',
      historyAdded: 'Agregado'
    },
    finance: {
      title: 'Resumen Financiero',
      selectPeriod: 'Seleccionar período',
      periods: {
        today: 'Hoy',
        last7days: 'Últimos 7 días',
        last30days: 'Últimos 30 días',
        last3months: 'Últimos 3 meses',
        lastYear: 'Último año'
      },
      revenue: 'Ingresos',
      expenses: 'Gastos',
      balance: 'Saldo Mensual',
      margin: 'Margen',
      financialFlow: 'Flujo Financiero (Últimos 6 Meses)',
      comparePeriod: 'vs periodo anterior'
    }
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt');

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];

    for (const k of keys) {
      value = value?.[k];
    }

    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
